# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-access-analyzer
  description: This component is responsible for configuring AWS Identity and Access Management Access Analyzer within an AWS Organization
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




